# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0331dbdf2b6bf1349fe07191d4ba81990e4fd15cb33420099e7a6062d8e6f6b458fe1df2b5b11219ee4491e05a238f10f4cecadb4a7086313e1bd2616d992608

test:
  secret_key_base: acde4c58c0c9f39743204c0a671f7a7c87d19faf295f6fe6e404967d0557c65ba1d253ae90a7cfedf205c669c1caff8a67e85940f1a64e4c091dc014229a5ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
